import logging

# pyrefly: ignore [missing-import]
from odoo import _, api, fields, models
from odoo.exceptions import UserError, ValidationError
from odoo.osv import expression

_logger = logging.getLogger(__name__)


class MailMessage(models.Model):
    _inherit = "mail.message"

    user_vote = fields.Integer(
        string="User Vote",
        default=0,
        help="Vote status given by the user. 0: No vote, 1: Upvoted, -1: Downvoted.",
    )

    @api.model
    def _message_fetch(
        self,
        domain,
        *,
        thread=None,
        search_term=None,
        is_notification=None,
        before=None,
        after=None,
        around=None,
        limit=30,
    ):
        """Override to filter only LLM messages for llm.thread model.

        EN: For LLM threads, we only want to display messages that have an llm_role
            (user, assistant, tool), not system notifications or other message types
            that would clutter the AI conversation interface.
            Signature updated for Odoo 19 compatibility (thread, is_notification params).

        ES: Para hilos LLM, solo queremos mostrar mensajes que tengan un llm_role
            (user, assistant, tool), no notificaciones del sistema u otros tipos de
            mensaje que saturarían la interfaz de conversación de IA.
            Firma actualizada para compatibilidad con Odoo 19 (parámetros thread, is_notification).
        """
        # Check if this is for an llm.thread model
        # The thread object is available directly in Odoo 19
        is_llm_thread = False
        if thread and hasattr(thread, "_name") and thread._name == "llm.thread":
            is_llm_thread = True
        elif domain:
            is_llm_thread = any(
                condition[0] == "model"
                and condition[1] == "="
                and condition[2] == "llm.thread"
                for condition in domain
                if isinstance(condition, (list, tuple)) and len(condition) == 3
            )

        if is_llm_thread:
            # Add LLM role filter for LLM threads - only show messages with llm_role
            llm_role_filter = [("llm_role", "!=", False)]
            domain = expression.AND([domain, llm_role_filter])

        # Call parent method with all Odoo 19 keyword arguments
        return super()._message_fetch(
            domain,
            thread=thread,
            search_term=search_term,
            is_notification=is_notification,
            before=before,
            after=after,
            around=around,
            limit=limit,
        )

    def _extras_to_store(self, store, format_reply):
        """Add LLM-specific fields to the message store.

        EN: Uses store.add_model_values() to inject custom LLM fields into
            the mail.message store entries, compatible with Odoo 19 Store API.

        ES: Usa store.add_model_values() para inyectar campos LLM personalizados
            en las entradas del store de mail.message, compatible con la API Store de Odoo 19.
        """
        super()._extras_to_store(store, format_reply)

        for message in self:
            data = {}

            # Add LLM-specific fields
            if hasattr(message, "llm_role") and message.llm_role:
                data["llm_role"] = message.llm_role
                # Set is_note=True for LLM messages to get the right bubble style
                data["is_note"] = True

            if hasattr(message, "user_vote"):
                data["user_vote"] = message.user_vote

            if hasattr(message, "body_json") and message.body_json:
                data["body_json"] = message.body_json

            if data:  # Only add to store if we have data
                data["id"] = message.id
                store.add_model_values("mail.message", data)

    def set_user_vote(self, vote_value):
        """Sets the user vote on this message, performing validation checks."""
        self.ensure_one()
        if self.llm_role not in ("assistant", "tool"):
            raise UserError(
                _(
                    "Voting is only allowed on messages generated by the assistant or a tool."
                )
            )
        if not isinstance(vote_value, int) or vote_value not in [-1, 0, 1]:
            raise ValidationError(
                _(
                    "Invalid vote value. Must be an integer: 1 (up), -1 (down), or 0 (none)."
                )
            )
        # EN: Using sudo() to write the vote because the user might not have write access to the
        # message record itself, but is allowed to vote on the AI response quality.
        # ES: Usando sudo() para escribir el voto porque el usuario podría no tener acceso de escritura
        # al registro del mensaje en sí, pero se le permite votar sobre la calidad de la respuesta de la IA.
        self.sudo().write({"user_vote": vote_value})
